
#    /$$$$$$$              /$$     /$$     /$$                 /$$ /$$   /$$ /$$$$$$$
#    | $$__  $$            | $$    | $$    | $$                | $$| $$  / $$| $$__  $$
#    | $$  \ $$  /$$$$$$  /$$$$$$ /$$$$$$  | $$  /$$$$$$   /$$$$$$$|  $$/ $$/| $$  \ $$
#    | $$$$$$$  /$$__  $$|_  $$_/|_  $$_/  | $$ /$$__  $$ /$$__  $$ \  $$$$/ | $$$$$$$/
#    | $$__  $$| $$  \ $$  | $$    | $$    | $$| $$$$$$$$| $$  | $$  >$$  $$ | $$____/
#    | $$  \ $$| $$  | $$  | $$ /$$| $$ /$$| $$| $$_____/| $$  | $$ /$$/\  $$| $$
#    | $$$$$$$/|  $$$$$$/  |  $$$$/|  $$$$/| $$|  $$$$$$$|  $$$$$$$| $$  \ $$| $$
#    |_______/  \______/    \___/   \___/  |__/ \_______/ \_______/|__/  |__/|__/

#            by PattyXDHD with ♥

# Change the language
# default available: en_US, de_DE
language: 'en_US'

# XP points you earn per bottle
xpPerBottle: 7

# List of all sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# To use no sound, enter ‘NONE’ as the sound
sounds:
  use: true
  volume: 0.2
  successfulSound: 'ENTITY_PLAYER_LEVELUP'
  failSound: 'ENTITY_BAT_HURT'
  inventoryClickSound: 'UI_BUTTON_CLICK'
  helpSound: 'ENTITY_ITEM_PICKUP'
  failChangeGuiNumber: 'BLOCK_ANVIL_PLACE'

# disables the interaction and replaces it with the GUI
replaceInteractWithGUI: false

# Use a block interaction to fill XP bottles.
# List of all materials: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blockInteractFill:
  use: true
  block: 'EMERALD_BLOCK'
  usedItem: 'GLASS_BOTTLE'
  bottlesPerClick: 1
  infoTitleStayTime: 5

# Use a block interaction to Convert your XP-Bottles to normal XP
blockInteractConvert:
  use: true
  block: 'EMERALD_BLOCK'
  usedItem: 'EXPERIENCE_BOTTLE'

# Change the calculation quantity in the inventory.
inventory:
  minusAmountNormal: 1
  minusAmountShift: 10
  plusAmountNormal: 1
  plusAmountShift: 10