name: BottledXP
author: PattyXDHD
website: https://github.com/PattyXDHD/BottledXP
version: 1.0.5
main: de.pattyxdhd.bottledxp.BottledXP
api-version: 1.13

commands:
  bottledxp:
    aliases:
      - bxp

permissions:
  bottledxp.info:
    info: Use the info about ur xp

  bottledxp.info.other:
    info: Allow to see the info from another Player

  bottledxp.fill.completeLevel:
    info: Allows you to fill all your XP to Bottles

  bottledxp.fill.amount:
    info: Allows you to fill an exact amount of Bottles with XP

  bottledxp.reload:
    info: Allows you to reload the Plugin config.yml
    default: op

  bottledxp.gui:
    info: Allows you to open the XP-GUI

  bottledxp.interact:
    info: Allows you to interact for transfers your XP to Bottles

  bottledxp.interact.completeLevel:
    info: Allows you to interact for transfers all your XP to Bottles

  bottledxp.convert:
    info: Allows you to Convert all the XP-Bottles in your Inventory to normal XP

  bottledxp.info.*:
    children:
      bottledxp.info: true
      bottledxp.info.other: true

  bottledxp.fill.*:
    children:
      bottledxp.fill.amount: true
      bottledxp.fill.completeLevel: true

  bottledxp.interact.*:
    children:
      bottledxp.interact: true
      bottledxp.interact.completeLevel: true
